#!/usr/bin/env python3
"""Generate assets/{viscosity,steelworks,rivierlab}/ from the pinned
vendor/knitweb submodule (molgang/pages, formerly Knitweb/molgang).

Replaces the manual "change knitweb first, re-copy here" step in SYNC.md —
that step had no tooling and no CI signal, so a stale copy could ship
silently (proven this session: assets/steelworks/data/sites/
w1276333474.json had drifted from its source with nothing to catch it).

Usage:
    python3 assets/world/sync_from_knitweb.py          # regenerate in place
    python3 assets/world/sync_from_knitweb.py --check  # exit 1 on drift (CI gate)
"""
from __future__ import annotations

import filecmp
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent  # repo root
SRC = ROOT / "vendor" / "knitweb" / "web"
OUT = ROOT / "assets"

# Exact (substring, replacement) pairs reverse-engineered from the current
# committed copies — kept as an explicit, auditable list rather than a
# general regex, since the actual rule set is small and finite.
VISCOSITY_SUBS = [
    ('href="lab-3d.html">3D Lab</a>', 'href="../world/">Moleculia</a>'),
    ('href="index.html">← Bar</a>', 'href="../world/">← Wereld</a>'),
]
STEELWORKS_SUBS = [
    ('href="rivierlab.html">', 'href="../rivierlab/">'),
    ('href="viscosity-room.html">', 'href="../viscosity/">'),
    ("fetch('steelworks/data/index.json')", "fetch('data/index.json')"),
    ("fetch(`steelworks/data/sites/${use.id}.json`)", "fetch(`data/sites/${use.id}.json`)"),
]
RIVIERLAB_SUBS = [
    ('href="steelworks.html">', 'href="../steelworks/">'),
    ('href="viscosity-room.html">', 'href="../viscosity/">'),
    ('href="index.html">← Bar</a>', 'href="../world/">← Bar</a>'),
]


def _rewrite(src: Path, subs: list[tuple[str, str]]) -> str:
    text = src.read_text(encoding="utf-8")
    for old, new in subs:
        if old not in text:
            raise SystemExit(
                f"ERROR: expected substring not found in {src.name}: {old!r}\n"
                "The knitweb source changed shape — update the *_SUBS list above.")
        text = text.replace(old, new)
    return text


def build(out_root: Path) -> None:
    visc = out_root / "viscosity"
    visc.mkdir(parents=True, exist_ok=True)
    (visc / "index.html").write_text(_rewrite(SRC / "viscosity-room.html", VISCOSITY_SUBS), encoding="utf-8")
    shutil.copy(SRC / "viscosity-sim.js", visc / "viscosity-sim.js")
    shutil.copy(SRC / "quest-input.js", visc / "quest-input.js")

    steel = out_root / "steelworks"
    steel.mkdir(parents=True, exist_ok=True)
    (steel / "index.html").write_text(_rewrite(SRC / "steelworks.html", STEELWORKS_SUBS), encoding="utf-8")
    shutil.copy(SRC / "quest-input.js", steel / "quest-input.js")
    shutil.copytree(SRC / "steelworks" / "data", steel / "data", dirs_exist_ok=True)

    river = out_root / "rivierlab"
    river.mkdir(parents=True, exist_ok=True)
    (river / "index.html").write_text(_rewrite(SRC / "rivierlab.html", RIVIERLAB_SUBS), encoding="utf-8")
    shutil.copy(SRC / "quest-input.js", river / "quest-input.js")


def _tree_diff(generated: Path, committed: Path) -> list[str]:
    diffs: list[str] = []

    def walk(cmp: filecmp.dircmp, rel: str) -> None:
        for name in cmp.diff_files:
            diffs.append(f"MODIFIED: {rel}{name}")
        for name in cmp.left_only:
            diffs.append(f"MISSING in committed copy: {rel}{name}")
        for name in cmp.right_only:
            diffs.append(f"EXTRA in committed copy (not generated by this script): {rel}{name}")
        for name, sub in cmp.subdirs.items():
            walk(sub, f"{rel}{name}/")

    walk(filecmp.dircmp(generated, committed), "")
    return diffs


def main() -> int:
    check = "--check" in sys.argv
    if not (SRC / "steelworks.html").exists():
        print("ERROR: vendor/knitweb submodule not checked out (run: git submodule update --init)")
        return 1

    if check:
        with tempfile.TemporaryDirectory() as tmp:
            build(Path(tmp))
            diffs = []
            for name in ("viscosity", "steelworks", "rivierlab"):
                diffs += _tree_diff(Path(tmp) / name, OUT / name)
        if diffs:
            print(f"ERROR: {len(diffs)} file(s) out of sync with vendor/knitweb:")
            for d in diffs:
                print(f"  {d}")
            print("Fix: python3 assets/world/sync_from_knitweb.py")
            return 1
        print("OK: assets/{viscosity,steelworks,rivierlab} match vendor/knitweb")
        return 0

    for name in ("viscosity", "steelworks", "rivierlab"):
        shutil.rmtree(OUT / name, ignore_errors=True)
    build(OUT)
    print("OK: regenerated assets/{viscosity,steelworks,rivierlab} from vendor/knitweb")
    return 0


if __name__ == "__main__":
    sys.exit(main())
